[package]
name = "netchannel"
version = "0.2.0"
authors = ["The Infinigryd Development Team"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "netchannel"
path = "src/netchannel.rs"

[dependencies]
log = "0"